name: Vercel Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    strategy:
      matrix:
        vercel-cli-version: ["vercel@latest", "https://vercel-git-tootallnate-zero-1527-bug-we-should-look-into-9b5350.vercel.sh/tarballs/vercel.tgz"]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        id: setup-node
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          yarn install --immutable
          npm install -g ${{ matrix.vercel-cli-version }}
          vercel --version

      - name: Pull Vercel project
        run: vercel pull --environment production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project
        run: vercel deploy --prod --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
