name: Vercel Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        id: setup-node
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./services/my-app
        run: |
          yarn install --immutable
          npm install -g vercel

      - name: Pull Vercel project
        working-directory: ./services/my-app
        run: vercel pull --environment production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        working-directory: ./services/my-app
        run: vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project
        working-directory: ./services/my-app
        run: vercel deploy --prod --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
